import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { buildAnnualPlan } from "@shared/annualPlan";
import { EMPTY_PROFILE, type WealthProfile } from "@shared/wealth";
import { CalendarDays, CircleAlert, Loader2, RefreshCw, ShieldCheck } from "lucide-react";

const categoryColor = { "積立": "bg-[#E3F6ED] text-[#237255]", "税制": "bg-[#EEF1FF] text-[#4C5EAB]", "教育": "bg-[#FFF1DD] text-[#936017]", "住宅": "bg-[#F5EAFE] text-[#8152A0]", "見直し": "bg-[#F0F3F1] text-[#586D63]", "保留": "bg-[#FDE9E5] text-[#A94732]" } as const;
const statusColor = { "実行": "bg-[#FDE9E5] text-[#A94732]", "確認": "bg-[#FFF1DD] text-[#936017]", "待機": "bg-[#E5F4EA] text-[#347257]" } as const;

export default function AnnualPlan() {
  const profileQuery = trpc.profile.get.useQuery();
  const profile = profileQuery.data?.payload ? JSON.parse(profileQuery.data.payload) as WealthProfile : EMPTY_PROFILE;
  const plan = buildAnnualPlan(profile, { lastMarketRefreshAt: profileQuery.data?.lastMarketRefreshAt });
  return <DashboardLayout><main className="space-y-6"><header className="flex flex-col justify-between gap-4 border-b border-[#DADFD9] pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#5A7970]">OPERATING SYSTEM</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#152524]">年間実行計画</h1><p className="mt-2 text-sm text-[#6A7672]">買う前に守る資金を確認し、税制・教育・住宅ローンの予定を同じカレンダーで運用します。</p></div><div className="rounded-xl bg-[#E5F4EA] px-4 py-3 text-xs text-[#356B56]">自動判定: 月次市場更新後</div></header>
  {profileQuery.isLoading ? <div className="grid h-[420px] place-items-center"><Loader2 className="animate-spin text-[#579178]"/></div> : <><section className="rounded-2xl bg-[#E5F4EA] px-5 py-4 text-sm text-[#285E49]">自動判定の結論: <b>{plan.executionPriority}</b>。現金・教育・金利・実配分・市場データ鮮度のうち、最も保守的な状態を優先します。</section><section className="grid gap-5 lg:grid-cols-3">{plan.triggers.map(trigger => <div key={trigger.id} className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-[#748078]">{trigger.label}</p><h2 className="mt-1 font-serif text-xl text-[#1B2E2B]">{trigger.status}</h2></div><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${statusColor[trigger.status]}`}>{trigger.status}</span></div><p className="mt-4 text-sm leading-6 text-[#3D5148]">{trigger.action}</p><p className="mt-3 text-[11px] text-[#4A8270]">提案への反映: {trigger.effect}</p><p className="mt-2 border-t border-[#EEF1EE] pt-3 text-[11px] text-[#77837D]">{trigger.detail} ・ 条件: {trigger.threshold}</p></div>)}</section>
  <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5 sm:p-6"><div className="flex gap-3"><CalendarDays className="text-[#3C8A68]"/><div><h2 className="font-serif text-2xl text-[#1B2E2B]">1月から12月の行動カレンダー</h2><p className="mt-1 text-xs leading-5 text-[#728078]">買付・保留・リバランス・税制・見直しを各月に明示し、月次の安全判定で上書きします。</p></div></div><div className="mt-5 space-y-3">{plan.annualActions.map((item, index) => <div key={`${item.month}-${item.category}`} className="flex gap-4 rounded-2xl bg-[#F7F9F7] p-4"><div className="w-12 shrink-0 pt-0.5 font-mono text-xs text-[#5F7169]">{item.month}月</div><div className="min-w-0"><span className={`rounded-full px-2 py-1 text-[10px] ${categoryColor[item.category]}`}>{item.category}</span><p className="mt-2 text-sm leading-6 text-[#273A34]">{item.action}</p>{item.trigger && <p className="mt-2 text-[11px] text-[#7A857E]">条件: {item.trigger}</p>}</div><span className="ml-auto self-start text-xs text-[#839088]">{index + 1}</span></div>)}</div></div>
  <aside className="space-y-5"><section className="rounded-[1.5rem] bg-[#142725] p-6 text-white"><RefreshCw className="text-[#A9EDCE]"/><h2 className="mt-4 font-serif text-2xl">自動見直しの仕組み</h2><p className="mt-3 text-sm leading-7 text-white/70">月次更新後に、現金バッファ、教育不足、配分乖離、金利、マクロデータ鮮度を確認します。安全条件に反する場合は「買い増し」ではなく「保留」を提示します。</p></section><section className="rounded-[1.5rem] border border-[#F0D8B4] bg-[#FFF9EF] p-6"><div className="flex gap-3"><CircleAlert className="shrink-0 text-[#AC7431]"/><div><h2 className="font-serif text-xl text-[#594117]">繰上返済の位置付け</h2><p className="mt-2 text-xs leading-6 text-[#795C29]">教育・防衛資金を使ってまで先に行いません。住宅ローン控除の残存、金利上昇、余剰現金の3点がそろった場合にだけ比較し、アプリは実行せず判断材料だけを表示します。</p></div></div></section><section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-6"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-[#3C8A68]"/><p className="text-xs leading-6 text-[#61736A]">税額・教育費・年金・金利は年次書類で更新してください。推奨は条件付きのモデル結果であり、投資成果や控除額を保証するものではありません。</p></div></section></aside></section></>}
  </main></DashboardLayout>;
}
