import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { formatPercent } from "@shared/wealth";
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, CircleAlert, Loader2, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";

function RetryButton({ onClick, loading = false, label = "再取得する" }: { onClick: () => void; loading?: boolean; label?: string }) {
  return <button onClick={onClick} className="inline-flex h-10 items-center gap-2 rounded-xl border border-[#D5DDD7] bg-white px-4 text-sm font-medium text-[#41514C] hover:border-[#9AB5A8] disabled:opacity-60" disabled={loading}><RefreshCw size={14} className={loading ? "animate-spin" : ""}/>{label}</button>;
}

export default function BacktestComparison() {
  const backtestQuery = trpc.market.backtest.useQuery(undefined, { retry: 3, staleTime: 6 * 60 * 60 * 1000 });
  const data = backtestQuery.data;
  const [isSlow, setIsSlow] = useState(false);
  useEffect(() => { setIsSlow(false); if (!backtestQuery.isLoading) return; const timer = window.setTimeout(() => setIsSlow(true), 10_000); return () => window.clearTimeout(timer); }, [backtestQuery.isLoading]);
  const retry = () => { setIsSlow(false); void backtestQuery.refetch(); };

  return <DashboardLayout><main className="space-y-6">
    <header className="flex flex-col justify-between gap-4 border-b border-[#DADFD9] pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#5A7970]">過去検証の比較</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#152524]">配分別バックテスト</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#6A7672]">世界株コア・現保有に近い代理配分・防御型を、同じ代理資産、月次リバランス、1か月の情報ラグで比較します。</p></div><RetryButton onClick={retry} loading={backtestQuery.isFetching} label="再取得"/></header>
    {backtestQuery.isLoading ? <section className="grid min-h-[420px] place-items-center rounded-[1.5rem] border border-[#DCE7DF] bg-white p-6 text-center"><div>{isSlow ? <><CircleAlert className="mx-auto text-[#A96D29]"/><h2 className="mt-4 font-serif text-2xl text-[#5C431A]">取得に時間がかかっています</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#6B716C]">過去検証データの取得を続けています。通信状態を確認し、必要なら再取得してください。資産の保存内容は変更されません。</p><div className="mt-5"><RetryButton onClick={retry}/></div></> : <><Loader2 className="mx-auto animate-spin text-[#579178]"/><p className="mt-4 text-sm text-[#60756A]">過去検証データを読み込んでいます</p></>}</div></section> : !data ? <section className="rounded-[1.5rem] border border-[#F0D6A6] bg-[#FFF9EF] p-6 text-center"><CircleAlert className="mx-auto text-[#A96D29]"/><h2 className="mt-3 font-serif text-2xl text-[#5C431A]">市場データを取得できませんでした</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-[#7B5C2B]">通信状態を確認して、時間を置いて再取得してください。資産残高や保存済みの方針は変更されません。</p><div className="mt-5"><RetryButton onClick={retry}/></div></section> : <>
      <section className="rounded-[1.5rem] bg-[#142725] p-6 text-white"><div className="flex gap-3"><ShieldCheck className="mt-1 text-[#A9EDCE]"/><div><h2 className="font-serif text-2xl">検証期間 {data.start} 〜 {data.asOf}</h2><p className="mt-3 text-sm leading-7 text-white/70">固定ウェイト比較であり、過去に最も良かった商品・戦略を選び出すものではありません。各月末の公開価格を観測し、翌月に月次リバランスする情報ラグを置いています。</p></div></div></section>
      <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-[1.5rem] border border-[#DDE5DE] bg-white p-5 sm:p-6"><h2 className="font-serif text-2xl text-[#1B2E2B]">累積価値の比較</h2><div className="mt-5 h-[300px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.chart}><CartesianGrid vertical={false} stroke="#E8ECE7"/><XAxis dataKey="date" tickFormatter={value => String(value).slice(0, 4)} tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: "#78847E" }}/><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: "#78847E" }}/><Tooltip formatter={(value: number) => value.toFixed(2)}/><Legend/><Area type="monotone" dataKey="core" name="世界株コア" stroke="#2A9D72" fill="#CFEFDF" fillOpacity={.45} strokeWidth={2}/><Area type="monotone" dataKey="portfolio" name="現保有に近い代理" stroke="#739CF4" fill="transparent" strokeWidth={2}/><Area type="monotone" dataKey="defensive" name="防御型" stroke="#D6A341" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></section><section className="rounded-[1.5rem] border border-[#E6D5B5] bg-[#FFF9EF] p-6"><div className="flex gap-3"><CircleAlert className="mt-1 shrink-0 text-[#A96D29]"/><div><h2 className="font-serif text-2xl text-[#5C431A]">比較の読み方</h2><p className="mt-3 text-xs leading-6 text-[#7B5C2B]">過去の年率や最大下落は将来の期待リターンではありません。配分ごとの下落耐性・値動きの違いを確認し、教育・生活防衛資金をリスク資産に混ぜないための補助として使います。</p></div></div></section></section>
      <section className="rounded-[1.5rem] border border-[#DDE5DE] bg-white p-5 sm:p-6"><h2 className="font-serif text-2xl text-[#1B2E2B]">固定配分ごとの結果</h2><div className="mt-5 grid gap-4 lg:grid-cols-3">{data.comparisons.map(item => <article key={item.id} className="rounded-2xl bg-[#F7F9F7] p-5"><p className="font-serif text-xl text-[#1C332C]">{item.name}</p><p className="mt-2 text-xs leading-5 text-[#66776F]">{item.description}</p><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="text-[10px] text-[#728078]">年率換算</p><p className="mt-1 font-serif text-2xl text-[#287556]">{formatPercent(item.metrics.cagr)}</p></div><div><p className="text-[10px] text-[#728078]">最大下落</p><p className="mt-1 font-serif text-2xl text-[#A76B28]">{formatPercent(item.metrics.maxDrawdown)}</p></div></div><p className="mt-4 border-t border-[#E5ECE5] pt-3 text-[11px] text-[#62736A]">世界株 {formatPercent(item.weights.world)} / 日本株 {formatPercent(item.weights.japan)} / 債券 {formatPercent(item.weights.bond)} / 金 {formatPercent(item.weights.gold)}</p></article>)}</div></section>
      <section className="rounded-[1.5rem] border border-[#DDE5DE] bg-[#F8FAF8] p-5"><div className="flex gap-3"><BarChart3 className="mt-1 shrink-0 text-[#3C8A68]"/><div><h2 className="font-serif text-xl text-[#1B2E2B]">方法と限界</h2><div className="mt-3 space-y-2">{data.limitations.map(item => <p key={item} className="text-xs leading-6 text-[#61736A]">{item}</p>)}</div><p className="mt-3 text-xs leading-6 text-[#61736A]">代理資産: {data.proxyWeights.map(item => `${item.proxy}（${item.label}）`).join(" / ")}。共通モデル費用 年{formatPercent(data.annualFeeRate)}。</p></div></div></section>
    </>}
  </main></DashboardLayout>;
}
