import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { buildAccountInputAlerts } from "@shared/accountInputAlerts";
import { buildCashTransferInstructions } from "@shared/cashTransferInstructions";
import { buildFamilyMonthlyChecklist, recordFamilyMonthlyChecklist, type FamilyChecklistStep } from "@shared/familyMonthlyChecklist";
import { buildMonthlyBalanceUpdateStatus } from "@shared/monthlyBalanceUpdateStatus";
import { buildMonthlyCashFlowPresentation } from "@shared/monthlyCashFlowPresentation";
import { buildMonthlyFundingStatus } from "@shared/fundingStatus";
import { buildCommandTasks, toggleCommandTask, type CommandTask } from "@shared/monthlyTasks";
import { buildRecommendation } from "@shared/recommendation";
import { EMPTY_PROFILE, formatCompactYen, summarizeCurrentAssets, type WealthProfile } from "@shared/wealth";
import { AlertTriangle, ArrowRight, BookOpenText, ChevronRight, CircleAlert, CircleCheck, Landmark, Loader2, PanelTop, ShieldAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const stateStyle = { do: "bg-[#DDF5E6] text-[#24724D]", hold: "bg-[#FBE7E3] text-[#A54B3E]", review: "bg-[#FFF0CE] text-[#8B5F19]" } as const;
const stateLabel = { do: "今月する", hold: "今月はしない", review: "確認する" } as const;

function ShellCard({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-[#D9E1DA] bg-white ${className}`}>{children}</section>; }

function Metric({ label, value, note, tone = "default" }: { label: string; value: string; note: string; tone?: "default" | "dark" | "warn" }) {
  const colors = tone === "dark" ? "bg-[#132D27] text-white border-[#132D27]" : tone === "warn" ? "bg-[#FFF9F0] border-[#F0D5A7]" : "bg-white border-[#D9E1DA]";
  return <div className={`rounded-2xl border p-4 ${colors}`}><p className={`text-[10px] font-semibold tracking-[0.13em] ${tone === "dark" ? "text-[#A9EDCE]" : "text-[#738078]"}`}>{label}</p><p className="mt-3 font-serif text-3xl tracking-tight">{value}</p><p className={`mt-2 text-[11px] leading-5 ${tone === "dark" ? "text-white/60" : "text-[#65746C]"}`}>{note}</p></div>;
}

function DecisionRow({ task, onDecide, busy }: { task: CommandTask; onDecide: (value: "accepted" | "held") => void; busy: boolean }) {
  const decisionLabel = task.decision === "accepted" ? "方針を記録済み" : task.decision === "held" ? "今月は見送り" : "未記録";
  return <article className="border-b border-[#E7ECE7] px-5 py-5 last:border-b-0 sm:px-6"><div className="flex flex-col gap-4 lg:grid lg:grid-cols-[1fr_auto] lg:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${stateStyle[task.state]}`}>{stateLabel[task.state]}</span><span className="text-[10px] tracking-wide text-[#748078]">{task.due} · {decisionLabel}</span></div><h3 className="mt-3 text-base font-semibold text-[#173028]">{task.title}</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-[#5B6D63]">{task.guidance.recommendation}</p><details className="mt-3 rounded-xl bg-[#F6F8F6] px-4 py-3 text-xs text-[#586B61]"><summary className="cursor-pointer font-semibold text-[#284E40]">理由・見直す条件・終わったといえる状態</summary><div className="mt-3 grid gap-2 leading-5 md:grid-cols-2"><p><b>理由:</b> {task.guidance.rationale}</p><p><b>見直す条件:</b> {task.guidance.changesWhen}</p><p><b>先に確認:</b> {task.guidance.check}</p><p><b>お金の扱い:</b> {task.guidance.money}</p><p className="md:col-span-2"><b>終わったといえる状態:</b> {task.guidance.completion}</p></div></details></div><div className="flex shrink-0 flex-wrap gap-2 lg:justify-end"><Button disabled={busy} onClick={() => onDecide("accepted")} className={`rounded-lg ${task.decision === "accepted" ? "bg-[#1E6849]" : "bg-[#17362C] hover:bg-[#284B42]"}`}>{task.decision === "accepted" ? "記録を戻す" : "この方針で進める"}</Button><Button disabled={busy} onClick={() => onDecide("held")} variant="outline" className={`rounded-lg border-[#D8C99D] ${task.decision === "held" ? "bg-[#FFF4DE]" : "bg-white"}`}>{task.decision === "held" ? "記録を戻す" : "今月は見送る"}</Button></div></div></article>;
}

export default function CommandCenter() {
  const [, setLocation] = useLocation();
  const [asOf] = useState(() => new Date().toISOString());
  const [profile, setProfile] = useState<WealthProfile>(EMPTY_PROFILE);
  const profileQuery = trpc.profile.get.useQuery();
  const saveMutation = trpc.profile.save.useMutation({ onError: () => toast.error("判断の保存に失敗しました。もう一度お試しください。") });

  useEffect(() => { if (!profileQuery.data?.payload) return; try { setProfile(JSON.parse(profileQuery.data.payload) as WealthProfile); } catch { toast.error("資産データの読み込みに失敗しました。"); } }, [profileQuery.data?.payload]);

  const funding = useMemo(() => buildMonthlyFundingStatus(profile), [profile]);
  const tasks = useMemo(() => buildCommandTasks(profile, asOf), [profile, asOf]);
  const recommendation = useMemo(() => buildRecommendation(profile), [profile]);
  const assets = useMemo(() => summarizeCurrentAssets(profile), [profile]);
  const transfers = useMemo(() => buildCashTransferInstructions(profile), [profile]);
  const inputAlerts = useMemo(() => buildAccountInputAlerts(profile, new Date(asOf)), [profile, asOf]);
  const balanceUpdate = useMemo(() => buildMonthlyBalanceUpdateStatus(profile, asOf), [profile, asOf]);
  const familyChecklist = useMemo(() => buildFamilyMonthlyChecklist(profile, asOf, inputAlerts.length, transfers.summary), [profile, asOf, inputAlerts.length, transfers.summary]);
  const cashFlow = useMemo(() => buildMonthlyCashFlowPresentation(profile), [profile]);
  const openDecisions = tasks.filter(task => !task.completed).length;
  const urgentPurposes = funding.cashPurposes.filter(item => item.status === "funding");
  const decisionStatus = inputAlerts.length ? { label: "入力の確認が必要", text: `口座情報の確認が${inputAlerts.length}件あります`, icon: <ShieldAlert size={17}/>, color: "text-[#9A5F19] bg-[#FFF4DF] border-[#EECF95]" } : transfers.requiresSetup ? { label: "口座設定が必要", text: "実口座の入力が先です", icon: <ShieldAlert size={17}/>, color: "text-[#9A5F19] bg-[#FFF4DF] border-[#EECF95]" } : funding.fundingGap > 0 ? { label: "現金計画を確認", text: "現金計画を先に調整", icon: <AlertTriangle size={17}/>, color: "text-[#A54B3E] bg-[#FFF3F0] border-[#ECC0B9]" } : { label: "判断の準備完了", text: "今月の判断を記録", icon: <CircleCheck size={17}/>, color: "text-[#236F4E] bg-[#EFF9F2] border-[#C9E7D2]" };

  const decide = (task: CommandTask, decision: "accepted" | "held") => { const previous = profile; const next = toggleCommandTask(profile, task, decision); setProfile(next); saveMutation.mutate({ payload: JSON.stringify(next) }, { onSuccess: () => toast.success(decision === "accepted" ? "方針を記録しました" : "今月は見送ると記録しました"), onError: () => setProfile(previous) }); };
  const completeFamilyChecklist = (step: FamilyChecklistStep, completedBy: "本人" | "配偶者" | "二人で確認") => { const previous = profile; const next = recordFamilyMonthlyChecklist(profile, asOf, step.id, completedBy); setProfile(next); saveMutation.mutate({ payload: JSON.stringify(next) }, { onSuccess: () => toast.success(`${step.title}を記録しました`), onError: () => setProfile(previous) }); };

  if (profileQuery.isLoading) return <DashboardLayout><main className="grid min-h-[65vh] place-items-center"><div className="text-center"><Loader2 className="mx-auto animate-spin text-[#3F8B68]"/><p className="mt-3 text-sm text-[#64746B]">ポジションと月次判断を読み込んでいます</p></div></main></DashboardLayout>;

  return <DashboardLayout><main className="mx-auto max-w-7xl space-y-6 pb-12">
    <header className="rounded-2xl bg-[#132D27] px-6 py-6 text-white sm:px-8 sm:py-7"><div className="flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-semibold tracking-[0.18em] text-[#A9EDCE]">今月の資産運用チェック · 手動入力</p><h1 className="mt-3 font-serif text-4xl tracking-tight sm:text-5xl">今月の判断</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/65">この画面は「今月、何を決めるか」だけを扱います。資産全体、現金の安全性、実行準備、投資提案を分けて確認し、詳しい根拠は必要なときだけ開きます。</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => setLocation("/accounts")} className="rounded-lg bg-[#9EE7CB] text-[#132D27] hover:bg-[#B8F3D9]"><Landmark size={16}/>口座残高を更新</Button><Button onClick={() => setLocation("/portfolio-audit")} variant="outline" className="rounded-lg border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white"><PanelTop size={16}/>保有・配分を見る</Button></div></div></header>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="資産合計" value={formatCompactYen(assets.total)} note="入力済みの現金と運用資産の合計" tone="dark"/><Metric label="すぐ使える現金" value={formatCompactYen(assets.cash)} note="すぐ使える現金として記録された額"/><Metric label="今月の残り余力" value={cashFlow.isCashFlowDeficit ? `−${formatCompactYen(cashFlow.deficitAmount)}` : formatCompactYen(funding.unallocatedMonthlySurplus)} note={cashFlow.isCashFlowDeficit ? "月内の資金不足。投資より先に調整" : "現金計画と投資設定の後に残る月内余力"} tone={cashFlow.isCashFlowDeficit ? "warn" : "default"}/><Metric label="今月の未決定" value={`${openDecisions}件`} note="今月、進めるか見送るかを記録する項目" tone={openDecisions > 0 ? "warn" : "default"}/></section>

    <section className={`flex flex-col gap-3 rounded-2xl border px-5 py-4 sm:flex-row sm:items-center sm:justify-between ${decisionStatus.color}`}><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-white/70">{decisionStatus.icon}</div><div><p className="text-[10px] font-semibold tracking-[0.14em]">{decisionStatus.label}</p><p className="mt-1 text-sm font-semibold">{decisionStatus.text}</p></div></div><p className="max-w-2xl text-xs leading-5 opacity-80">{inputAlerts.length ? "残高の基準日や口座名が未入力、または古い口座があります。今月の振替額は参考値として扱い、先に口座・現金画面で更新してください。" : transfers.requiresSetup ? "実際に使う銀行名と口座名を入力すると、出金元・入金先・金額を口座単位で再計算します。" : funding.fundingGap > 0 ? "生活費・現金目標・投資設定を同時に満たせていません。今月の投資提案は見送ります。" : "現金目標を先に確認したうえで、今月の提案を採用するか見送るか記録してください。"}</p></section>

    <ShellCard className={balanceUpdate.isCompleted ? "border-[#C9E4D2] bg-[#F5FBF7]" : "border-[#D9E1DA]"}><div className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl text-base font-semibold ${balanceUpdate.isCompleted ? "bg-[#2E8058] text-white" : "bg-[#EEF4EF] text-[#2E6C4C]"}`}>{balanceUpdate.isCompleted ? "✓" : `${balanceUpdate.updatedCount}/${balanceUpdate.totalCount}`}</span><div><p className="text-[10px] font-semibold tracking-[0.16em] text-[#5C7C70]">月次残高の更新状況</p><h2 className="mt-1 text-base font-semibold text-[#173028]">{balanceUpdate.isCompleted ? "今月の残高更新は記録済みです" : `今月の残高更新は ${balanceUpdate.updatedCount} / ${balanceUpdate.totalCount}口座です`}</h2><p className="mt-1 text-xs leading-5 text-[#60736A]">{balanceUpdate.isCompleted ? `${new Date(balanceUpdate.completion!.completedAt).toLocaleDateString("ja-JP")}に完了として保存されています。` : "すべての口座で今月の基準日を入力すると、口座・現金画面から完了記録を残せます。"}</p></div></div><Button onClick={() => setLocation("/accounts")} variant="outline" className="shrink-0 rounded-lg">{balanceUpdate.isCompleted ? "更新状況を見る" : "残高を更新する"} <ChevronRight size={16}/></Button></div></ShellCard>

    {inputAlerts.length > 0 && <ShellCard className="border-[#EAC9BC] bg-[#FFF9F5]"><div className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[10px] font-semibold tracking-[0.16em] text-[#A54B3E]">残高入力の確認</p><h2 className="mt-2 font-serif text-xl text-[#4A2F28]">先に更新したい口座があります</h2><div className="mt-3 space-y-2">{inputAlerts.slice(0, 3).map(alert => <p key={alert.id} className="text-xs leading-5 text-[#754D42]"><span className={`mr-2 inline-block rounded-full px-2 py-0.5 text-[10px] font-semibold ${alert.severity === "red" ? "bg-[#F9DED8] text-[#A3493C]" : "bg-[#FFF0CF] text-[#916019]"}`}>{alert.severity === "red" ? "入力が必要" : "更新を確認"}</span>{alert.title}</p>)}</div></div><Button onClick={() => setLocation("/accounts")} variant="outline" className="shrink-0 rounded-lg border-[#DAB3A7] bg-white">口座・現金を更新 <ChevronRight size={16}/></Button></div></ShellCard>}

    <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <ShellCard><div className="flex items-end justify-between border-b border-[#E6EBE6] px-5 py-5 sm:px-6"><div><p className="text-[10px] font-semibold tracking-[0.16em] text-[#5C7C70]">今月の判断リスト</p><h2 className="mt-2 font-serif text-2xl text-[#173028]">今月の判断</h2><p className="mt-1 text-xs text-[#65766D]">採用・見送りの記録だけを行います。銀行振込や買付注文は実行しません。</p></div><span className="rounded-lg bg-[#F0F5F1] px-3 py-2 text-xs text-[#315A48]">未決定 {openDecisions}件</span></div><div>{tasks.map(task => <DecisionRow key={task.key} task={task} onDecide={decision => decide(task, decision)} busy={saveMutation.isPending}/>)}</div></ShellCard>
      <div className="space-y-5"><ShellCard className="overflow-hidden"><div className="border-b border-[#E6EBE6] px-5 py-5"><p className="text-[10px] font-semibold tracking-[0.16em] text-[#5C7C70]">投資に回すお金</p><h2 className="mt-2 font-serif text-2xl text-[#173028]">新規資金の行き先</h2></div><div className="space-y-3 p-5">{recommendation.monthlyProductRecommendations.map(item => <div key={item.id} className="rounded-xl border border-[#DCE6DF] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] text-[#6B7B73]">{item.account}</p><p className="mt-1 text-sm font-semibold text-[#1B342B]">{item.fundName}</p></div><span className="rounded-full bg-[#E4F5E9] px-2 py-1 text-[10px] font-semibold text-[#26724E]">{item.status}</span></div><p className="mt-3 font-serif text-2xl text-[#17362C]">{item.monthlyAmount.toLocaleString("ja-JP")}円 <span className="font-sans text-xs text-[#60746A]">/ 月</span></p><p className="mt-2 text-xs leading-5 text-[#5C7167]">{item.instruction}</p></div>)}<Button onClick={() => setLocation("/portfolio-audit")} variant="outline" className="w-full rounded-lg">保有と配分を確認 <ChevronRight size={16}/></Button></div></ShellCard>
        <ShellCard><div className="px-5 py-5"><p className="text-[10px] font-semibold tracking-[0.16em] text-[#5C7C70]">今月の口座操作</p><h2 className="mt-2 font-serif text-2xl text-[#173028]">目的別の振替指示</h2><p className="mt-2 text-xs leading-5 text-[#60736A]">{transfers.summary}</p><div className="mt-4 space-y-3">{transfers.instructions.length ? transfers.instructions.map(instruction => <div key={instruction.id} className={`rounded-xl border p-4 ${instruction.status === "insufficient-source-balance" ? "border-[#E9C98B] bg-[#FFF9EE]" : instruction.status === "ready" ? "border-[#D6E6DC] bg-[#F6FAF7]" : "border-[#E8D0C7] bg-[#FFF8F5]"}`}><div className="flex items-start justify-between gap-3"><p className="text-xs font-semibold text-[#294D3E]">{instruction.purpose}</p><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${instruction.status === "ready" ? "bg-[#E1F2E6] text-[#26704D]" : instruction.status === "insufficient-source-balance" ? "bg-[#FFF0CA] text-[#926019]" : "bg-[#F9E1DB] text-[#A54B3E]"}`}>{instruction.status === "ready" ? "振替候補" : instruction.status === "insufficient-source-balance" ? "残高が不足" : "先に口座を入力"}</span></div><p className="mt-2 font-serif text-xl text-[#17362C]">{formatCompactYen(instruction.amount)} <span className="font-sans text-[11px] text-[#66776F]">/ 今月移せる額</span></p>{instruction.amount !== instruction.requestedAmount && <p className="mt-1 text-[11px] text-[#946019]">本来の目安 {formatCompactYen(instruction.requestedAmount)} ・残り {formatCompactYen(instruction.requestedAmount - instruction.amount)}</p>}<p className="mt-2 text-xs leading-5 text-[#60736A]">{instruction.action}</p></div>) : <div className="rounded-xl bg-[#F6F8F6] p-4 text-xs text-[#60736A]">今月、追加の現金移動はありません。</div>}<Button onClick={() => setLocation("/accounts")} className="w-full rounded-lg bg-[#17362C] hover:bg-[#284B42]"><Landmark size={16}/>口座と残高を更新</Button></div></div></ShellCard>
      </div>
    </section>

    <section className="grid gap-5 lg:grid-cols-3"><ShellCard className="p-5"><p className="text-[10px] font-semibold tracking-[0.16em] text-[#5C7C70]">現金目標の確認</p><h2 className="mt-2 font-serif text-xl text-[#173028]">現金目標の警告</h2><div className="mt-4 space-y-3">{urgentPurposes.length ? urgentPurposes.map(item => <div key={item.id} className="flex gap-3 border-t border-[#E6EBE6] pt-3 first:border-t-0 first:pt-0"><CircleAlert className="mt-0.5 shrink-0 text-[#C18024]" size={16}/><div><p className="text-sm font-semibold">{item.label}</p><p className="mt-1 text-xs text-[#61736A]">不足 {formatCompactYen(item.gap)} · {item.due}</p></div></div>) : <p className="text-sm text-[#61736A]">現金目標に未対応の警告はありません。</p>}</div></ShellCard>
      <ShellCard className="p-5"><p className="text-[10px] font-semibold tracking-[0.16em] text-[#5C7C70]">保有商品の確認</p><h2 className="mt-2 font-serif text-xl text-[#173028]">保有と配分</h2><p className="mt-4 text-sm leading-6 text-[#61736A]">現在の保有商品、株式・債券・金の配分、追加停止の商品を一つの一覧で確認します。</p><Button onClick={() => setLocation("/portfolio-audit")} variant="outline" className="mt-5 w-full rounded-lg">ポートフォリオを開く <ArrowRight size={16}/></Button></ShellCard>
      <ShellCard className="p-5"><p className="text-[10px] font-semibold tracking-[0.16em] text-[#5C7C70]">提案を確かめる</p><h2 className="mt-2 font-serif text-xl text-[#173028]">提案の根拠</h2><p className="mt-4 text-sm leading-6 text-[#61736A]">商品比較、バックテスト、シミュレーション、制度・費用の前提はここで確認します。日々の判断画面には混ぜません。</p><Button onClick={() => setLocation("/recommendation")} variant="outline" className="mt-5 w-full rounded-lg">根拠を開く <BookOpenText size={16}/></Button></ShellCard>
    </section>

    <ShellCard className="p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-semibold tracking-[0.16em] text-[#5C7C70]">二人で行う月1回の確認</p><h2 className="mt-2 font-serif text-2xl text-[#173028]">夫婦の月次チェックリスト</h2><p className="mt-1 text-xs leading-5 text-[#60736A]">残高、口座操作、今月の方針を順に確認します。記録はこの月だけに残り、振替や注文は実行しません。</p></div><span className="rounded-lg bg-[#EEF5F0] px-3 py-2 text-xs text-[#315A48]">完了 {familyChecklist.filter(step => step.completed).length} / {familyChecklist.length}</span></div><div className="mt-5 grid gap-3 lg:grid-cols-3">{familyChecklist.map((step, index) => <article key={step.id} className={`rounded-2xl border p-4 ${step.completed ? "border-[#C9E4D2] bg-[#F5FBF7]" : "border-[#DCE7DF] bg-white"}`}><div className="flex items-start gap-3"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs font-semibold ${step.completed ? "bg-[#2E8058] text-white" : "bg-[#E9F1EB] text-[#2F644D]"}`}>{step.completed ? "✓" : index + 1}</span><div><h3 className="text-sm font-semibold text-[#1C372D]">{step.title}</h3><p className="mt-2 text-xs leading-5 text-[#61736A]">{step.detail}</p></div></div>{step.completed ? <p className="mt-4 rounded-lg bg-white px-3 py-2 text-[11px] text-[#39735C]">{step.completed.completedBy} · {new Date(step.completed.completedAt).toLocaleDateString("ja-JP")}に記録</p> : <div className="mt-4 flex flex-wrap gap-2"><Button disabled={saveMutation.isPending} onClick={() => completeFamilyChecklist(step, "本人")} size="sm" variant="outline" className="rounded-lg text-[11px]">本人</Button><Button disabled={saveMutation.isPending} onClick={() => completeFamilyChecklist(step, "配偶者")} size="sm" variant="outline" className="rounded-lg text-[11px]">配偶者</Button><Button disabled={saveMutation.isPending} onClick={() => completeFamilyChecklist(step, "二人で確認")} size="sm" className="rounded-lg bg-[#17362C] text-[11px] hover:bg-[#284B42]">二人で確認</Button></div>}</article>)}</div></ShellCard>
  </main></DashboardLayout>;
}
