import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { buildRecommendation } from "@shared/recommendation";
import { EMPTY_PROFILE, formatCompactYen, formatPercent, type WealthProfile } from "@shared/wealth";
import { BadgeInfo, Calculator, ChevronRight, CircleAlert, Landmark, Loader2, Percent, Scale, ShieldCheck } from "lucide-react";

const decisionStyle = { "長期コア候補": "bg-[#DDF4E6] text-[#1F704F]", "定額候補": "bg-[#E8EDFF] text-[#4055A8]", "追加停止": "bg-[#FDE9E5] text-[#A94732]", "保有のみ": "bg-[#FFF1DD] text-[#936017]" } as const;

export default function DecisionEvidence() {
  const profileQuery = trpc.profile.get.useQuery();
  const macroQuery = trpc.market.macro.useQuery(undefined, { staleTime: 10 * 60 * 1000, retry: 2 });
  const profile = profileQuery.data?.payload ? JSON.parse(profileQuery.data.payload) as WealthProfile : EMPTY_PROFILE;
  const result = buildRecommendation(profile, macroQuery.data?.asOf ?? profileQuery.data?.lastMarketRefreshAt?.toISOString());
  const returns = result.returnComparison;
  const centralTaxSaving = returns.idecoTaxSavingRange.central;
  return <DashboardLayout><main className="space-y-6"><header className="flex flex-col justify-between gap-4 border-b border-[#DADFD9] pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#5A7970]">DECISION EVIDENCE</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#152524]">実質年利と選定根拠</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#6A7672]">年利は商品ごとの予言ではなく、資産配分のモデル入力です。税制・控除・流動性を同じ表示面で比較し、採用と不採用の理由を残します。</p></div><div className="rounded-xl bg-[#E5F4EA] px-4 py-3 text-xs text-[#356B56]">市場基準日: {new Date(result.comparisonScope.sourceAsOf).toLocaleDateString("ja-JP")}</div></header>
  {profileQuery.isLoading ? <div className="grid h-[420px] place-items-center"><Loader2 className="animate-spin text-[#579178]"/></div> : <><section className="rounded-[2rem] bg-[#142725] p-7 text-white sm:p-9"><div className="grid gap-7 xl:grid-cols-[1.25fr_.75fr]"><div><p className="eyebrow text-[#A9EDCE]">MODELLED RETURN — NOT A FORECAST</p><h2 className="mt-3 font-serif text-3xl">推奨配分の期待名目年率 <span className="text-[#A9EDCE]">{formatPercent(returns.grossExpected)}</span></h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/70">株式・債券・金のモデル前提、目標配分、年率0.20%の費用から計算した比較値です。実際の将来年利、値動き、分配金、為替、税額を保証しません。</p><div className="mt-6 grid grid-cols-3 gap-3"><DarkMetric label="株式" value={formatPercent(result.recommended.weights.equity)}/><DarkMetric label="債券" value={formatPercent(result.recommended.weights.bonds)}/><DarkMetric label="金" value={formatPercent(result.recommended.weights.gold)}/></div></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-xs text-white/50">iDeCoの所得控除・感応度</p><p className="mt-2 font-serif text-3xl text-[#A9EDCE]">年 {formatCompactYen(centralTaxSaving)}</p><p className="mt-3 text-xs leading-6 text-white/65">掛金年{formatCompactYen(returns.idecoTaxSavingRange.annualContribution)}に、合算限界税率20%を仮定した年税負担軽減の比較値です。12%〜30%の範囲では年{formatCompactYen(returns.idecoTaxSavingRange.low)}〜{formatCompactYen(returns.idecoTaxSavingRange.high)}。これは運用年利には混ぜません。</p></div></div></section>
  <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Panel><SectionTitle icon={<Percent/>} title="期間別の期待年利レンジ" text="10%点・90%点は正規分布近似の年率換算レンジ。時間が長いほど年率のレンジが狭く見えますが、途中の損失や制度変更のリスクは消えません。"/><div className="mt-5 grid gap-3 sm:grid-cols-3">{returns.bands.map(item => <div key={item.horizonYears} className="rounded-2xl bg-[#F6F8F5] p-4"><p className="text-xs text-[#687A72]">{item.horizonYears === 27 ? "退職まで" : `${item.horizonYears}年`}の年率換算</p><p className="mt-2 font-serif text-3xl text-[#1A4033]">{formatPercent(item.expectedAnnualNominal)}</p><p className="mt-3 text-[11px] text-[#65766E]">10%点 {formatPercent(item.p10Annualized)}<br/>90%点 {formatPercent(item.p90Annualized)}</p></div>)}</div></Panel><Panel><SectionTitle icon={<Calculator/>} title="保有口座ごとの税後比較" text="同じモデル期待リターンでも、税制と引出制限で実質的な使いやすさが変わります。"/><div className="mt-5 space-y-3">{returns.vehicles.map(item => <div key={item.id} className="rounded-2xl bg-[#F6F8F5] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-[#203831]">{item.label}</p><p className="mt-1 text-[11px] leading-5 text-[#66776F]">{item.taxBenefitNote}</p></div><div className="shrink-0 text-right"><p className="font-serif text-xl text-[#237256]">{formatPercent(item.expectedAnnualAfterTax)}</p><p className="text-[10px] text-[#708079]">流動性 {item.liquidity}</p></div></div></div>)}</div></Panel></section>
  <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Panel><SectionTitle icon={<Landmark/>} title="繰上返済の実質年利" text="繰上返済の利息削減は、元本返済後に資金を取り戻せない点を除けば確定的です。控除期間中は、金利から控除相当分を差し引く単純化モデルで表示します。"/><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="border-b border-[#E2E9E2] text-[#697A72]"><tr><th className="pb-3 pr-5">条件</th><th className="pb-3 pr-5">ローン金利</th><th className="pb-3 pr-5">控除調整</th><th className="pb-3">実質年利</th></tr></thead><tbody>{returns.prepayment.map(item => <tr key={item.label} className="border-b border-[#EEF2EE]"><td className="py-4 pr-5 font-medium text-[#263C34]">{item.label}</td><td className="py-4 pr-5">{formatPercent(item.loanRate)}</td><td className="py-4 pr-5">-{formatPercent(item.creditAdjustment)}</td><td className="py-4 font-serif text-lg text-[#215D49]">{formatPercent(item.effectiveAnnualReturn)}</td></tr>)}</tbody></table></div><p className="mt-4 rounded-xl bg-[#FFF5E6] p-3 text-[11px] leading-5 text-[#805B29]">{returns.prepayment[0]?.decisionGuardrail} 実際の控除額は年末残高、所得税額・住民税枠、住宅区分、入居年で変わります。</p></Panel><Panel className="border-[#E6D5B5] bg-[#FFF9EF]"><SectionTitle icon={<CircleAlert className="text-[#A66E28]"/>} title="比較の範囲" text={result.comparisonScope.analyzed}/><p className="mt-4 text-sm font-medium leading-6 text-[#7D5724]">{result.comparisonScope.exclusions}</p><p className="mt-4 border-t border-[#F0DFC5] pt-4 text-xs leading-6 text-[#745E3E]">選定ルール: {result.comparisonScope.selectionRule}</p></Panel></section>
  <section className="rounded-[1.5rem] border border-[#DDE5DE] bg-white p-5 sm:p-6"><SectionTitle icon={<Scale/>} title="商品を選ぶまでの比較・検証" text="「最も儲かる商品」を断定するのではなく、家計上の役割・既存保有との重複・費用・制度適合性を順に比較した記録です。"/><div className="mt-5 grid gap-4 xl:grid-cols-2">{result.productEvidence.map(item => <article key={item.id} className="rounded-2xl border border-[#E2E9E2] p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-serif text-xl text-[#1C332C]">{item.name}</h3><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-medium ${decisionStyle[item.decision]}`}>{item.decision}</span></div><Detail label="採用・不採用の根拠" text={item.rationale}/><Detail label="比較した軸" text={item.comparedWith}/><Detail label="比較外・不確実性" text={item.excludedReason}/><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs text-[#287556] underline">公式資料を確認 <ChevronRight size={14}/></a></article>)}</div></section>
  <section className="rounded-[1.5rem] border border-[#DDE5DE] bg-[#F8FAF8] p-5 sm:p-6"><div className="flex gap-3"><ShieldCheck className="mt-1 shrink-0 text-[#3C8A68]"/><div><h2 className="font-serif text-2xl text-[#1A3029]">前提と限界</h2><div className="mt-3 space-y-2">{returns.methodology.map(item => <p key={item} className="text-xs leading-6 text-[#61736A]">{item}</p>)}</div><p className="mt-4 text-xs leading-6 text-[#61736A]">出所・比較範囲の詳細はプロジェクト内の <span className="font-mono">docs/recommendation_methodology_sources.md</span> に記録しています。注文・売買はこのアプリから実行しません。</p></div></div></section></>}
  </main></DashboardLayout>;
}

function DarkMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/[.08] p-4"><p className="text-[10px] text-white/45">{label}</p><p className="mt-2 font-serif text-2xl text-[#A9EDCE]">{value}</p></div>; }
function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-[1.5rem] border border-[#DDE5DE] bg-white p-5 sm:p-6 ${className}`}>{children}</section>; }
function SectionTitle({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="flex gap-3"><div className="mt-1 text-[#3C8A68]">{icon}</div><div><h2 className="font-serif text-2xl text-[#1B2E2B]">{title}</h2><p className="mt-1 text-xs leading-5 text-[#728078]">{text}</p></div></div>; }
function Detail({ label, text }: { label: string; text: string }) { return <div className="mt-4"><p className="text-[10px] font-medium tracking-wide text-[#52816D]">{label}</p><p className="mt-1 text-xs leading-5 text-[#60726A]">{text}</p></div>; }
