import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { buildFundingComparison } from "@shared/fundingComparison";
import { EMPTY_PROFILE, formatCompactYen, formatPercent, type WealthProfile } from "@shared/wealth";
import { ArrowDownRight, GraduationCap, Home, Loader2, Scale, ShieldCheck } from "lucide-react";

function Metric({ icon, label, value, note }: { icon: React.ReactNode; label: string; value: string; note: string }) {
  return <section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5"><div className="text-[#3C8A68]">{icon}</div><p className="mt-4 text-xs text-[#728078]">{label}</p><p className="mt-2 font-serif text-3xl text-[#1B2E2B]">{value}</p><p className="mt-3 text-xs leading-5 text-[#687A72]">{note}</p></section>;
}

export default function FundingPlan() {
  const profileQuery = trpc.profile.get.useQuery();
  const profile = profileQuery.data?.payload ? JSON.parse(profileQuery.data.payload) as WealthProfile : EMPTY_PROFILE;
  const comparison = buildFundingComparison(profile);
  return <DashboardLayout><main className="space-y-6"><header className="flex flex-col justify-between gap-4 border-b border-[#DADFD9] pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#5A7970]">FUNDING ORDER</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#152524]">教育費と繰上返済</h1><p className="mt-2 text-sm text-[#6A7672]">同じ現金を二度使わないために、目的資金・金利・税制を同じ条件で比較します。</p></div><div className="rounded-xl bg-[#FFF3DF] px-4 py-3 text-xs text-[#87601B]">現在の優先: {comparison.priority}</div></header>
  {profileQuery.isLoading ? <div className="grid h-[420px] place-items-center"><Loader2 className="animate-spin text-[#579178]"/></div> : <><section className="grid gap-5 lg:grid-cols-3"><Metric icon={<GraduationCap/>} label="教育費の月次積立目安" value={formatCompactYen(comparison.educationMonthlyNeed)} note="私立高校・私立大学（自宅）を、各開始時点までに安全資産で確保する仮定。"/><Metric icon={<ArrowDownRight/>} label="投資後の年次余剰" value={formatCompactYen(comparison.annualFreeCash)} note="既知支出、NISA、iDeCo後の概算。未入力の臨時費は別途要確認。"/><Metric icon={<Home/>} label="繰上返済の流動性条件" value={comparison.mortgage.liquidityGuardrail ? "充足" : "未充足"} note="生活防衛12か月と教育積立必要額を満たさない間は繰上返済を行わない。"/></section>
  <section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-5"><section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5 sm:p-6"><div className="flex gap-3"><GraduationCap className="text-[#3C8A68]"/><div><h2 className="font-serif text-2xl text-[#1B2E2B]">教育資金の到達点</h2><p className="mt-1 text-xs leading-5 text-[#728078]">到達時点が近づくほど、預金・個人向け国債など安全資産へ寄せる前提です。</p></div></div><div className="mt-5 space-y-3">{comparison.education.map(item => <div key={`${item.child}-${item.milestone}`} className="grid gap-3 rounded-2xl bg-[#F7F9F7] p-4 sm:grid-cols-[.75fr_1fr_1fr_1fr]"><p className="font-medium text-[#2C4039]">{item.child}</p><p className="text-sm text-[#53665D]">{item.milestone}</p><p className="text-sm text-[#53665D]">開始まで約{item.years}年</p><p className="text-sm text-[#2C7355]">{formatCompactYen(item.monthlyNeed)}/月</p></div>)}</div></section><section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5 sm:p-6"><h2 className="font-serif text-2xl text-[#1B2E2B]">金利ストレスと税引後比較</h2><p className="mt-2 text-xs leading-5 text-[#728078]">年{formatPercent(comparison.investment.grossExpectedReturn)}の期待リターンを、NISA非課税と課税口座の税引後に分けて比較します。</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{comparison.mortgage.scenarios.map(item => <div key={item.label} className="rounded-2xl bg-[#F7F9F7] p-4"><p className="text-xs text-[#52665E]">{item.label} / {formatPercent(item.rate)}</p><p className="mt-2 text-sm text-[#2C4039]">控除中: {formatPercent(item.netPrepaymentReturnDuringCredit)}</p><p className="mt-1 text-sm text-[#2C4039]">控除後: {formatPercent(item.netPrepaymentReturnAfterCredit)}</p><p className="mt-2 text-[11px] text-[#5B7C70]">NISAとの差 {formatPercent(item.nisaReturnGap)} / 課税口座との差 {formatPercent(item.taxableReturnGap)}</p><p className="mt-3 text-[11px] leading-5 text-[#6B7772]">{item.action}</p></div>)}</div><p className="mt-4 text-[11px] leading-5 text-[#6B7772]">{comparison.investment.note}</p></section></div><aside className="space-y-5"><section className="rounded-[1.5rem] bg-[#142725] p-6 text-white"><Scale className="text-[#A9EDCE]"/><h2 className="mt-4 font-serif text-2xl">現在の比較結論</h2><p className="mt-3 text-sm leading-7 text-white/75">{comparison.explanation}</p></section><section className="rounded-[1.5rem] border border-[#F0D8B4] bg-[#FFF9EF] p-6"><h2 className="font-serif text-xl text-[#594117]">繰上返済を検討する条件</h2><p className="mt-2 text-xs leading-6 text-[#795C29]">教育費の月次積立を満たし、生活防衛資金が12か月分以上あり、住宅ローン控除が終了または金利が大幅に上がった時に、預金・投資・繰上返済を再比較します。</p></section><section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-6"><div className="flex gap-3"><ShieldCheck className="shrink-0 text-[#3C8A68]"/><p className="text-xs leading-6 text-[#61736A]">比較は金利・控除・流動性をモデル化したものです。教育方針、奨学金、親族援助、実際の所得税・住民税によって結果は変わります。</p></div></section></aside></section></>}
  </main></DashboardLayout>;
}
