import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { buildHouseholdOpportunity } from "@shared/householdOpportunity";
import { EMPTY_PROFILE, formatCompactYen, type WealthProfile } from "@shared/wealth";
import { ArrowRight, CircleAlert, HandCoins, HeartHandshake, Loader2, ShieldCheck } from "lucide-react";

const priorityColor = { "最優先": "bg-[#DFF5E7] text-[#1F7250]", "優先": "bg-[#FFF0D8] text-[#925E16]", "比較": "bg-[#EDEFF3] text-[#58636E]" } as const;
const liquidityColor = { "高": "text-[#237357]", "中": "text-[#866019]", "低": "text-[#A34535]" } as const;

export default function HouseholdOpportunity() {
  const profileQuery = trpc.profile.get.useQuery();
  const profile = profileQuery.data?.payload ? JSON.parse(profileQuery.data.payload) as WealthProfile : EMPTY_PROFILE;
  const model = buildHouseholdOpportunity(profile);
  return <DashboardLayout><main className="space-y-6"><header className="border-b border-[#DADFD9] pb-6"><p className="eyebrow text-[#5A7970]">HOUSEHOLD OPPORTUNITY</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#152524]">暮らしを守る資金配分</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#66756E]">同額をどこに回すかを、税後期待値だけでなく、引出しやすさ、教育資金、住宅ローン、家族の生活満足度まで含めて比較します。</p></header>
  {profileQuery.isLoading ? <div className="grid h-[420px] place-items-center"><Loader2 className="animate-spin text-[#579178]"/></div> : <><section className="rounded-[1.6rem] bg-[#142725] p-6 text-white"><div className="flex gap-3"><HeartHandshake className="shrink-0 text-[#A9EDCE]"/><div><p className="text-xs tracking-[.16em] text-[#A9EDCE]">現在の優先順位</p><h2 className="mt-2 font-serif text-2xl">{model.recommendation}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-white/70">生活防衛資金の不足: {formatCompactYen(model.cashShortfall)} / 教育資金バケツの不足: {formatCompactYen(model.educationShortfall)}。投資枠を埋めることより、必要時に売却しないで済む状態を優先します。</p></div></div></section>
  <section className="grid gap-4 lg:grid-cols-3"><Metric label="既知の月間支出" value={formatCompactYen(model.monthlyKnownSpend)} note="生活費、コープ、共済、住宅ローンの入力値。"/><Metric label="防衛資金の不足" value={formatCompactYen(model.cashShortfall)} note="既知の月間支出12か月分を基準に計算。"/><Metric label="教育資金の不足" value={formatCompactYen(model.educationShortfall)} note="私立高校・私立大学（自宅）の設定値を基準に計算。"/></section>
  <section className="space-y-4">{model.opportunities.map(item => <article key={item.id} className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-medium ${priorityColor[item.priority]}`}>{item.priority}</span><span className={`text-xs font-medium ${liquidityColor[item.liquidity]}`}>流動性: {item.liquidity}</span></div><h2 className="mt-3 font-serif text-2xl text-[#1D322B]">{item.label}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#4C6259]">{item.action}</p></div><div className="grid gap-3 sm:grid-cols-2 lg:w-[420px]"><div className="rounded-2xl bg-[#F4F8F5] px-5 py-4"><p className="text-[10px] text-[#6D7F75]">10年後・基準シナリオ</p><p className="mt-2 font-serif text-2xl text-[#245C46]">{formatCompactYen(item.tenYearNominalValue)}</p></div><div className="rounded-2xl bg-[#FFF4EF] px-5 py-4"><p className="text-[10px] text-[#906354]">10年後・下振れ比較</p><p className="mt-2 font-serif text-2xl text-[#9C4635]">{formatCompactYen(item.downsideTenYearValue)}</p></div></div></div><div className="mt-4 grid gap-3 border-t border-[#EDF1EE] pt-4 lg:grid-cols-2"><div className="flex items-start gap-2 text-xs leading-5 text-[#6A7B72]"><ShieldCheck size={15} className="mt-0.5 shrink-0 text-[#3B8B68]"/>{item.caveat}</div><div className="flex items-start gap-2 text-xs leading-5 text-[#8A5A4E]"><CircleAlert size={15} className="mt-0.5 shrink-0 text-[#B55A43]"/>{item.downsideRisk}</div></div></article>)}</section>
  <section className="rounded-[1.5rem] border border-[#F0D8B4] bg-[#FFF9EF] p-5 sm:p-6"><div className="flex gap-3"><CircleAlert className="shrink-0 text-[#A87928]"/><div><h2 className="font-serif text-xl text-[#604716]">この比較値の読み方</h2><p className="mt-2 text-xs leading-6 text-[#745D2E]">{model.methodology} NISA・iDeCo・繰上返済・預金は交換可能な商品ではありません。NISA/iDeCoの税制、実際の金利、家計支出、教育方針に応じて月次で更新します。注文・売買は実行しません。</p></div></div></section><div className="flex items-center gap-2 text-xs text-[#6B7D74]"><HandCoins size={15}/>金額の比較は「何を買うか」より先に「生活を脅かさず、いつ使う資金か」を確認するためのものです。<ArrowRight size={14}/></div></>}
  </main></DashboardLayout>;
}

function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5"><p className="text-xs text-[#708078]">{label}</p><p className="mt-3 font-serif text-3xl text-[#1B312C]">{value}</p><p className="mt-3 text-xs leading-5 text-[#6E7E75]">{note}</p></section>; }
