import DashboardLayout from "@/components/DashboardLayout";
import RecommendationReasonTooltip from "@/components/RecommendationReasonTooltip";
import ProductPerformanceDialog from "@/components/ProductPerformanceDialog";
import { trpc } from "@/lib/trpc";
import { buildIdecoComparison } from "@shared/idecoComparison";
import { buildIdecoTooltipEvidence } from "@shared/recommendationTooltips";
import { EMPTY_PROFILE, formatPercent, type WealthProfile } from "@shared/wealth";
import { ArrowUpRight, CheckCircle2, CircleAlert, Coins, Loader2, ShieldCheck } from "lucide-react";

const statusStyle = { "定額候補": "bg-[#DDF4E6] text-[#1F704F]", "代替候補": "bg-[#E8EDFF] text-[#4055A8]", "サテライト": "bg-[#FFF1DD] text-[#936017]", "見送り": "bg-[#FDE9E5] text-[#A94732]", "移行確認": "bg-[#F2EAFB] text-[#7750A0]" } as const;

export default function IdecoUniverse() {
  const profileQuery = trpc.profile.get.useQuery();
  const profile = profileQuery.data?.payload ? JSON.parse(profileQuery.data.payload) as WealthProfile : EMPTY_PROFILE;
  const result = buildIdecoComparison(profile);
  return <DashboardLayout><main className="space-y-6"><header className="flex flex-col justify-between gap-4 border-b border-[#DADFD9] pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#5A7970]">SBI iDeCo SELECT PLAN</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#152524]">iDeCo 全候補比較</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#6A7672]">公式公開一覧で確認したセレクトプラン対象27本を、費用・資産クラス・既存保有との重複・60歳までの引出制限で比較します。将来成績のランキングではありません。</p></div><div className="rounded-xl bg-[#E5F4EA] px-4 py-3 text-xs text-[#356B56]">参照日: {result.asOf}</div></header>
  {profileQuery.isLoading ? <div className="grid h-[420px] place-items-center"><Loader2 className="animate-spin text-[#579178]"/></div> : <><section className="grid gap-5 lg:grid-cols-3"><Metric label="現行の新規配分候補" value={`${result.currentCount}本`} note="公式公開一覧のセレクトプラン対象。"/><Metric label="追加予定" value={`${result.additional.length}本`} note="2026年10月16日予定。追加前は配分先に選ばない。"/><Metric label="推奨する定額候補" value={result.currentFunds.find(item => item.decision === "定額候補")?.name ?? "—"} note="既存の国内株保有との重複を低くする長期iDeCo候補。"/></section>
  <section className="rounded-[1.5rem] bg-[#142725] p-6 text-white sm:p-7"><div className="flex gap-3"><ShieldCheck className="mt-1 text-[#A9EDCE]"/><div><h2 className="font-serif text-2xl">この家計に対する選定ロジック</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-white/72">{result.methodology}</p><p className="mt-3 text-xs leading-6 text-white/52">iDeCoは原則60歳まで引き出せません。生活防衛・教育資金・住宅維持資金には使わず、掛金月額20,000円の長期資金に限定して比較しています。</p></div></div></section>
  <section className="rounded-[1.5rem] border border-[#DDE5DE] bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="font-serif text-2xl text-[#1B2E2B]">現行の全候補</h2><p className="mt-1 text-xs leading-5 text-[#728078]">信託報酬は公式公開一覧で表示された年率。`以内`・`程度`の注記をそのまま残しています。</p></div><a href={result.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs text-[#287556] underline">SBI公式の入替情報 <ArrowUpRight size={14}/></a></div><div className="mt-5 overflow-x-auto"><table className="min-w-[900px] text-left text-xs"><thead className="border-b border-[#E2E9E2] text-[#697A72]"><tr><th className="pb-3 pr-4">商品</th><th className="pb-3 pr-4">分類 / 地域</th><th className="pb-3 pr-4">費用</th><th className="pb-3 pr-4">指数・方針</th><th className="pb-3">判定</th></tr></thead><tbody>{result.currentFunds.map(item => <tr key={item.id} className="border-b border-[#EEF2EE] align-top"><td className="py-4 pr-4 font-medium text-[#243A32]"><div className="flex items-center gap-1.5">{item.name}<RecommendationReasonTooltip evidence={buildIdecoTooltipEvidence(item)}/>{item.decision === "定額候補" && <ProductPerformanceDialog focusId="emaxis-ex-japan" compact/>}</div><p className="mt-1 max-w-xs text-[11px] font-normal leading-5 text-[#65766E]">{item.rationale}</p></td><td className="py-4 pr-4 text-[#50645B]">{item.category}<br/>{item.region}</td><td className="py-4 pr-4 text-[#2A7658]">{item.feeNote}</td><td className="py-4 pr-4 text-[#50645B]">{item.indexOrPolicy}</td><td className="py-4"><span className={`whitespace-nowrap rounded-full px-2 py-1 text-[10px] font-medium ${statusStyle[item.decision]}`}>{item.decision}</span></td></tr>)}</tbody></table></div></section>
  <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Panel title="追加予定の商品" icon={<Coins/>}><p className="text-xs leading-5 text-[#728078]">2026年10月16日予定の追加。テーマ・集中型・元本確保を含むため、追加後に目論見書と現在の配分を再確認してから比較します。</p><div className="mt-4 space-y-2">{result.additional.map(item => <div key={item.id} className="rounded-xl bg-[#F7F9F7] p-3"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-[#30453D]">{item.name}</p><span className="shrink-0 text-[10px] text-[#76539A]">{item.feeNote}</span></div><p className="mt-1 text-[11px] text-[#6D7B74]">{item.category} / {item.indexOrPolicy} — {item.rationale}</p></div>)}</div></Panel><Panel title="除外・移行確認" icon={<CircleAlert className="text-[#A96D29]"/>}><p className="text-xs leading-5 text-[#728078]">公式告知では、以下は2026年10月16日以降に新規買付停止予定です。保有は継続可能ですが、掛金配分を含む場合は2026年11月11日までに変更しないと未指図資産になる案内があります。</p><div className="mt-4 space-y-2">{result.scheduledRemoval.map(item => <div key={item.id} className="rounded-xl bg-[#FFF7E9] px-3 py-2 text-xs text-[#7D5A25]"><b>{item.name}</b><span className="ml-2 text-[#98733A]">{item.category} / {item.feeNote} / {item.selectPlanEligibility}</span></div>)}</div></Panel></section>
  <section className="rounded-[1.5rem] border border-[#DDE5DE] bg-[#F8FAF8] p-5"><div className="flex gap-3"><CheckCircle2 className="mt-1 shrink-0 text-[#3C8A68]"/><p className="text-xs leading-6 text-[#61736A]">比較の対象・方法・公式URLは <span className="font-mono">docs/sbi_ideco_universe_sources.md</span> に記録しています。商品名・費用・配分可否は変更され得るため、実際の加入者サイトで配分設定を行う前に必ず再確認してください。</p></div></section></>}
  </main></DashboardLayout>;
}
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5"><p className="text-xs text-[#728078]">{label}</p><p className="mt-2 font-serif text-2xl leading-8 text-[#1B2E2B]">{value}</p><p className="mt-3 text-xs leading-5 text-[#687A72]">{note}</p></section>; }
function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-[1.5rem] border border-[#DDE5DE] bg-white p-5 sm:p-6"><div className="flex gap-3"><span className="mt-1 text-[#3C8A68]">{icon}</span><h2 className="font-serif text-2xl text-[#1B2E2B]">{title}</h2></div><div className="mt-4">{children}</div></section>; }
