import DashboardLayout from "@/components/DashboardLayout";
import RecommendationReasonTooltip from "@/components/RecommendationReasonTooltip";
import ProductPerformanceDialog from "@/components/ProductPerformanceDialog";
import { trpc } from "@/lib/trpc";
import { buildNisaReview } from "@shared/nisaComparison";
import { buildNisaTooltipEvidence } from "@shared/recommendationTooltips";
import { EMPTY_PROFILE, formatCompactYen, formatPercent, type WealthProfile } from "@shared/wealth";
import { BadgeCheck, CircleAlert, ExternalLink, Globe2, Loader2, ShieldCheck } from "lucide-react";

const decisionColor = { "コア候補": "bg-[#DFF5E7] text-[#1F7250]", "保有継続の役割確認": "bg-[#E7EEFF] text-[#40569C]", "追加買付は保留": "bg-[#FCE8E4] text-[#A04A36]", "新規積立の比較候補": "bg-[#FFF1D9] text-[#8B5E18]" } as const;

export default function NisaUniverse() {
  const profileQuery = trpc.profile.get.useQuery();
  const profile = profileQuery.data?.payload ? JSON.parse(profileQuery.data.payload) as WealthProfile : EMPTY_PROFILE;
  const review = buildNisaReview(profile);
  return <DashboardLayout><main className="space-y-6"><header className="border-b border-[#DADFD9] pb-6"><p className="eyebrow text-[#5A7970]">NISA UNIVERSE & FIT</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#152524]">NISA全体比較</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#66756E]">公式の適格商品母集団を起点に、現在保有・広範囲分散コア・為替ヘッジ・長期債・金を目的、費用、重複、流動性で比較します。将来リターンで全商品を順位付けする画面ではありません。</p></header>
  {profileQuery.isLoading ? <div className="grid h-[420px] place-items-center"><Loader2 className="animate-spin text-[#579178]"/></div> : <><section className="grid gap-4 lg:grid-cols-4"><Stat label="つみたて投資枠の公式母集団" value={`${review.universe.tsumitateCount}本`} note={review.universe.breakdown}/><Stat label="基準日" value={review.universe.asOf} note="金融庁・資産運用業協会・東京証券取引所の届出一覧を適格性の根拠として使用。"/><Stat label="NISA残枠" value={review.allowance.state === "入力済み" ? formatCompactYen(review.allowance.totalRemaining ?? 0) : "未入力"} note={review.allowance.state === "入力済み" ? `買付履歴${review.allowance.purchaseCount}件。統合推奨・根拠で証券会社画面と照合。` : "統合推奨・根拠から年間枠と買付履歴を入力。"}/><Stat label="現在の追加買付判定" value={review.emergencyShortfall > 0 || review.allowance.totalRemaining === 0 ? "保留" : "目的別に比較"} note={review.emergencyShortfall > 0 ? `生活防衛資金の不足約${Math.round(review.emergencyShortfall / 10_000)}万円を優先。` : review.allowance.totalRemaining === 0 ? "入力済みのNISA残枠が0円。翌年まで新規買付を保留。" : "生活防衛資金の判定は通過。教育資金・配分乖離も併せて確認。"}/></section>
  <section className="rounded-[1.5rem] border border-[#D8E4DC] bg-[#F2FAF5] p-5 sm:p-6"><div className="flex gap-3"><Globe2 className="shrink-0 text-[#328761]"/><div><h2 className="font-serif text-2xl text-[#1B342B]">比較範囲の約束</h2><p className="mt-2 text-sm leading-6 text-[#48685A]">{review.universe.coverage}</p><p className="mt-2 text-xs leading-5 text-[#6B7D74]">{review.universe.growthScope}</p></div></div></section>
  <section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5 sm:p-6"><h2 className="font-serif text-2xl text-[#1B342B]">資金目的ごとの選定ルール</h2><p className="mt-2 text-xs leading-5 text-[#6C7B73]">同じNISA商品でも、資金を使う時期・目的で扱いを変えます。目的資金をリスク資産へ一律に振り分けません。</p><div className="mt-5 grid gap-3 lg:grid-cols-2">{review.purposeSelections.map(item => <div key={item.purpose} className="rounded-2xl bg-[#F7F9F7] p-4"><div className="flex items-center justify-between gap-3"><p className="font-medium text-[#294138]">{item.purpose}</p><span className="rounded-full bg-white px-2 py-1 text-[10px] text-[#547165]">{item.nisaRole}</span></div><p className="mt-3 text-xs leading-5 text-[#546961]">{item.rationale}</p>{item.selectedIds.length > 0 && <p className="mt-3 text-[11px] text-[#267258]">対象候補: {item.selectedIds.map(id => review.reviews.find(candidate => candidate.id === id)?.name).join(" / ")}</p>}</div>)}</div></section>
  <section className="space-y-4">{review.reviews.map(item => <article key={item.id} className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-medium ${decisionColor[item.decision]}`}>{item.decision}</span><span className="text-xs text-[#75837B]">{item.status}・{item.nisaEligibility}</span></div><div className="mt-3 flex items-center gap-2"><h2 className="font-serif text-2xl text-[#1D322B]">{item.name}</h2><RecommendationReasonTooltip evidence={buildNisaTooltipEvidence(item)}/>{(item.id === "2559" || item.id === "emaxis-ac") && <ProductPerformanceDialog focusId={item.id} compact/>}</div><p className="mt-2 text-sm leading-6 text-[#496159]">{item.rationale}</p></div><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-1 text-xs text-[#2B7657] underline underline-offset-4">公式資料 <ExternalLink size={13}/></a></div><div className="mt-5 grid gap-3 border-t border-[#EDF1EE] pt-5 sm:grid-cols-2 xl:grid-cols-4"><Meta label="資産・指数" value={`${item.assetClass} / ${item.benchmark}`}/><Meta label="為替方針・流動性" value={`${item.currencyPolicy} / ${item.liquidity}`}/><Meta label="費用" value={item.feeRate !== undefined ? `年${formatPercent(item.feeRate)}（${item.feeAsOf}）` : item.feeAsOf}/><Meta label="集中・重複" value={`${item.concentration}。${item.overlap}`}/></div><div className="mt-4 flex items-start gap-2 rounded-xl bg-[#F8FAF8] px-4 py-3 text-xs leading-5 text-[#63766D]"><BadgeCheck size={15} className="mt-0.5 shrink-0 text-[#3B8B68]"/><span>目的適合: {item.purposeFit.join("・")}</span></div></article>)}</section>
  <section className="rounded-[1.5rem] border border-[#F0D8B4] bg-[#FFF9EF] p-5 sm:p-6"><div className="flex gap-3"><CircleAlert className="shrink-0 text-[#A87928]"/><div><h2 className="font-serif text-xl text-[#604716]">比較の限界と注文前確認</h2><p className="mt-2 text-xs leading-6 text-[#745D2E]">{review.disclaimer} 信託報酬、NISA適格性、販売会社の取扱い、指数構成、為替ヘッジコストは変わり得ます。買付時点で最新の目論見書と証券会社画面を確認してください。</p></div></div></section></>}
  </main></DashboardLayout>;
}

function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5"><p className="text-xs text-[#708078]">{label}</p><p className="mt-3 font-serif text-2xl text-[#1B312C]">{value}</p><p className="mt-3 text-xs leading-5 text-[#6E7E75]">{note}</p></section>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] tracking-wide text-[#7A8981]">{label}</p><p className="mt-1 text-xs leading-5 text-[#3C5349]">{value}</p></div>; }
