import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { buildPortfolioAudit } from "@shared/portfolioAudit";
import { EMPTY_PROFILE, formatCompactYen, formatPercent, type WealthProfile } from "@shared/wealth";
import { AlertTriangle, ArrowRight, CircleCheck, Loader2, ShieldCheck } from "lucide-react";

const statusStyle = { "コア": "bg-[#DDF5E6] text-[#257257]", "保有": "bg-[#E9EEF8] text-[#4F6498]", "追加停止": "bg-[#FFF0DD] text-[#9A6420]" } as const;

export default function PortfolioAudit() {
  const profileQuery = trpc.profile.get.useQuery();
  const profile = profileQuery.data?.payload ? JSON.parse(profileQuery.data.payload) as WealthProfile : EMPTY_PROFILE;
  const audit = buildPortfolioAudit(profile);
  return <DashboardLayout><main className="mx-auto max-w-7xl space-y-6"><header className="rounded-2xl bg-[#132D27] px-6 py-6 text-white sm:flex sm:items-end sm:justify-between sm:px-8"><div><p className="text-[10px] font-semibold tracking-[0.18em] text-[#A9EDCE]">保有商品と買付方針</p><h1 className="mt-3 font-serif text-4xl tracking-tight">保有商品と新規資金の方針</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/65">保有商品を役割ごとに分け、重複と新規資金の行き先を確認します。売却を促す画面ではなく、今後の資金配分を決めるための確認画面です。</p></div><div className="mt-4 rounded-lg border border-white/15 bg-white/5 px-4 py-3 text-[10px] tracking-wide text-[#A9EDCE] sm:mt-0">この画面から注文はしません</div></header>
  {profileQuery.isLoading ? <div className="grid h-[420px] place-items-center"><Loader2 className="animate-spin text-[#579178]"/></div> : <><section className="grid gap-4 lg:grid-cols-3"><Allocation label="現在の株式" current={audit.current.equity} target={audit.target.equity}/><Allocation label="現在の債券" current={audit.current.bonds} target={audit.target.bonds}/><Allocation label="現在の金" current={audit.current.gold} target={audit.target.gold}/></section>
  <section className="rounded-2xl border border-[#DEE5DE] bg-white"><div className="flex gap-3 border-b border-[#E6EBE6] px-5 py-5 sm:px-6"><ShieldCheck className="text-[#3C8A68]"/><div><p className="text-[10px] font-semibold tracking-[0.16em] text-[#5C7C70]">持っている商品の一覧</p><h2 className="mt-2 font-serif text-2xl text-[#1B2E2B]">保有商品の役割と方針</h2><p className="mt-1 text-xs leading-5 text-[#728078]">「追加停止」は売却指示ではありません。新規資金をコア資産や目的別現金に優先配分する方針です。</p></div></div><div>{audit.audits.map(item => <div key={item.code} className="grid gap-3 border-b border-[#E7ECE7] px-5 py-5 last:border-b-0 md:grid-cols-[.7fr_.8fr_1.25fr_1.25fr] sm:px-6"><div><p className="text-xs text-[#748078]">{item.code}</p><p className="mt-1 font-medium text-[#20332E]">{item.name}</p></div><div><span className={`rounded-full px-2 py-1 text-[10px] ${statusStyle[item.status]}`}>{item.status}</span><p className="mt-2 text-xs text-[#52665D]">{item.role}</p></div><p className="text-xs leading-5 text-[#5B6E65]">{item.reason}</p><p className="text-xs leading-5 text-[#2E7355]">次の行動: {item.nextAction}</p></div>)}</div></section>
  <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="rounded-[1.5rem] bg-[#142725] p-6 text-white"><p className="eyebrow text-[#A9EDCE]">NEW MONEY ROUTING</p><h2 className="mt-3 font-serif text-3xl">新規資金の優先順位</h2><div className="mt-6 space-y-4">{audit.purchasePlan.map((item, index) => <div key={item.item} className="flex gap-4 border-t border-white/10 pt-4 first:border-t-0 first:pt-0"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-white/10 text-xs">{index + 1}</div><div><p className="font-medium">{item.item} <span className="ml-2 text-[#A9EDCE]">{formatCompactYen(item.amount)}/月</span></p><p className="mt-1 text-sm text-white/75">{item.action}</p><p className="mt-1 text-xs leading-5 text-white/45">{item.note}</p></div></div>)}</div></div><aside className="space-y-5"><section className="rounded-[1.5rem] border border-[#F0D8B4] bg-[#FFF9EF] p-6"><div className="flex gap-3"><AlertTriangle className="shrink-0 text-[#AC7431]"/><div><h2 className="font-serif text-xl text-[#594117]">教育費と繰上返済</h2><p className="mt-2 text-xs leading-6 text-[#795C29]">教育資金の不足見込みは{formatCompactYen(audit.educationShortfall)}です。これは株式の期待収益や繰上返済より先に、用途別の安全資産として扱います。</p></div></div></section><section className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-6"><CircleCheck className="text-[#3C8A68]"/><h2 className="mt-3 font-serif text-xl text-[#1B2E2B]">繰上返済の判断条件</h2><p className="mt-2 text-xs leading-6 text-[#61736A]">住宅ローン控除の残り、変動金利が現状から+1.0%を超えたか、生活防衛・教育資金を確保したかを満たすまで、比較対象に留めます。</p></section></aside></section></>}
  </main></DashboardLayout>;
}

function Allocation({ label, current, target }: { label: string; current: number; target: number }) { return <div className="rounded-[1.5rem] border border-[#DEE5DE] bg-white p-5"><p className="text-xs text-[#728078]">{label}</p><div className="mt-2 flex items-baseline justify-between"><p className="font-serif text-3xl text-[#1B2E2B]">{formatPercent(current)}</p><p className="text-xs text-[#63756C]">目標 {formatPercent(target)}</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#EDF1ED]"><div className="h-full rounded-full bg-[#4A9072]" style={{ width: `${Math.min(100, current * 100)}%` }}/></div></div>; }
