import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { buildRecommendation } from "@shared/recommendation";
import { buildGoalTimeline, summarizeMonthlyFunding } from "@shared/goalTimeline";
import { EMPTY_PROFILE, formatCompactYen, formatPercent, type WealthProfile } from "@shared/wealth";
import { AlertTriangle, CheckCircle2, Info, Loader2, ShieldCheck, Sparkles } from "lucide-react";

const priorityStyle = { "今月": "bg-[#17362C] text-white", "年内": "bg-[#E5F4EA] text-[#257257]", "条件付き": "bg-[#FFF3DF] text-[#936017]" } as const;

export default function Recommendation() {
  const profileQuery = trpc.profile.get.useQuery();
  const profile = profileQuery.data?.payload ? JSON.parse(profileQuery.data.payload) as WealthProfile : EMPTY_PROFILE;
  const result = buildRecommendation(profile);
  const funding = buildGoalTimeline(profile).monthlyFunding;
  const fundingSummary = summarizeMonthlyFunding(funding);

  return <DashboardLayout><main className="space-y-6"><header className="flex flex-col justify-between gap-4 border-b border-[#DADFD9] pb-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#5A7970]">OPTIMIZATION STUDIO</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#152524]">推奨プラン</h1><p className="mt-2 text-sm text-[#6A7672]">5,000経路の確率シミュレーションを、家計の資金用途と税制制約でふるいにかけます。</p></div><div className="rounded-xl bg-[#E5F4EA] px-4 py-3 text-xs text-[#356B56]">基準日: {new Date(result.asOf).toLocaleDateString("ja-JP")}</div></header>
    {profileQuery.isLoading ? <div className="grid h-[420px] place-items-center"><Loader2 className="animate-spin text-[#579178]"/></div> : <>
      <section className="overflow-hidden rounded-[2rem] bg-[#142725] p-7 text-white sm:p-9"><div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><div><p className="eyebrow text-[#A9EDCE]">Recommended portfolio</p><div className="mt-4 flex items-center gap-3"><Sparkles className="text-[#A9EDCE]"/><h2 className="font-serif text-3xl">{result.recommended.name}</h2></div><p className="mt-4 max-w-2xl text-sm leading-7 text-white/70">短中期の生活防衛・教育・住宅維持資金を現金バケツへ分けた後の長期投資部分に対する目標です。最大リターンではなく、目標到達確率と下落耐性の両方を評価します。</p><div className="mt-7 grid grid-cols-3 gap-3"><Metric label="株式" value={formatPercent(result.recommended.weights.equity)}/><Metric label="債券" value={formatPercent(result.recommended.weights.bonds)}/><Metric label="金" value={formatPercent(result.recommended.weights.gold)}/></div></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-xs text-white/50">目標到達確率（モデル内）</p><p className="mt-2 font-serif text-5xl text-[#A9EDCE]">{formatPercent(result.recommended.successRate)}</p><div className="mt-6 space-y-3 text-xs text-white/65"><p className="flex justify-between gap-3"><span>65歳時点の中央値</span><b className="text-white">{formatCompactYen(result.recommended.medianAtRetirement)}</b></p><p className="flex justify-between gap-3"><span>10パーセンタイル</span><b className="text-white">{formatCompactYen(result.recommended.percentile10AtRetirement)}</b></p><p className="flex justify-between gap-3"><span>中央値の最大下落</span><b className="text-white">{formatPercent(result.recommended.medianMaxDrawdown)}</b></p></div></div></div></section>
      <section className="grid gap-4 md:grid-cols-4"><Panel><p className="text-xs text-[#6C7A73]">教育・住宅等の現金積立</p><p className="mt-2 font-serif text-2xl text-[#1B312C]">{formatCompactYen(fundingSummary.cashReserveTotal)}</p><p className="mt-2 text-[10px] leading-5 text-[#718078]">年払い・防衛・教育・住宅維持を優先</p></Panel><Panel><p className="text-xs text-[#6C7A73]">iDeCoの月次候補</p><p className="mt-2 font-serif text-2xl text-[#1B312C]">{formatCompactYen(fundingSummary.ideco)}</p><p className="mt-2 text-[10px] leading-5 text-[#718078]">期限資金の充足後だけを対象</p></Panel><Panel className="md:col-span-2"><p className="text-xs text-[#6C7A73]">長期運用の月次候補</p><p className="mt-2 font-serif text-3xl text-[#1B312C]">{formatCompactYen(fundingSummary.longTermInvestment)}</p><p className="mt-2 text-[11px] leading-5 text-[#718078]">保存済みの本人年収から、生活費・年払い・教育・住宅維持を先に差し引いた残余です。NISA等の注文は実行しません。</p></Panel></section>
      <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Panel><Title title="ポートフォリオ候補の比較" text={`${result.paths.toLocaleString("ja-JP")}経路・${result.years}年の確率シミュレーション。数値は予測ではなく、前提ごとの比較です。`}/><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="border-b border-[#E3E8E3] text-[#64736C]"><tr><th className="pb-3 pr-5">候補</th><th className="pb-3 pr-5">株 / 債 / 金</th><th className="pb-3 pr-5">到達確率</th><th className="pb-3 pr-5">中央値</th><th className="pb-3">10%点</th></tr></thead><tbody>{result.candidates.map(candidate => <tr key={candidate.id} className={`border-b border-[#EEF1EE] ${candidate.id === result.recommended.id ? "bg-[#F0FAF4]" : ""}`}><td className="py-4 pr-5 font-semibold">{candidate.name}{candidate.id === result.recommended.id && <span className="ml-2 rounded-full bg-[#CEF0DC] px-2 py-1 text-[10px] text-[#247053]">推奨</span>}</td><td className="py-4 pr-5">{Math.round(candidate.weights.equity * 100)} / {Math.round(candidate.weights.bonds * 100)} / {Math.round(candidate.weights.gold * 100)}%</td><td className="py-4 pr-5">{formatPercent(candidate.successRate)}</td><td className="py-4 pr-5">{formatCompactYen(candidate.medianAtRetirement)}</td><td className="py-4">{formatCompactYen(candidate.percentile10AtRetirement)}</td></tr>)}</tbody></table></div></Panel><Panel><Title title="税制・流動性の比較" text="控除・非課税は制度上の利点であり、実際の税額は年次書類で確認します。"/><div className="mt-5 space-y-3">{result.taxComparison.map(item => <div key={item.action} className="rounded-xl bg-[#F6F8F5] p-4"><div className="flex justify-between gap-3"><p className="font-medium">{item.action}</p><span className="text-[10px] text-[#6B7D74]">流動性: {item.liquidity}</span></div><p className="mt-2 text-xs text-[#327055]">{item.estimatedBenefit}</p><p className="mt-2 text-[11px] leading-5 text-[#748078]">{item.caveat}</p></div>)}</div></Panel></section>
      <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Panel><Title title="合理性を優先した生活見直しプラン" text="金額を増やす前に、失敗時に売却しない構造を作る順番です。"/><div className="mt-5 space-y-4">{result.actionPlan.map((item, index) => <div key={item.priority} className="flex gap-4 rounded-2xl border border-[#E3E8E3] p-4"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#F2F5F1] font-mono text-xs">{index + 1}</div><div className="min-w-0"><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${priorityStyle[item.priority]}`}>{item.priority}</span><p className="mt-3 text-sm font-semibold leading-6">{item.action}</p><p className="mt-2 text-xs leading-5 text-[#5F7169]">根拠: {item.reason}</p><p className="mt-1 text-xs leading-5 text-[#8A6738]">トレードオフ: {item.tradeoff}</p></div></div>)}</div></Panel><div className="space-y-5"><Panel><div className="flex gap-3"><Info className="mt-1 shrink-0 text-[#507C6E]"/><div><Title title="収入前提" text={`${result.incomeContext.sourceTaxYear ? `令和${result.incomeContext.sourceTaxYear - 2018}年分の源泉徴収票` : "保存済みの家計プロフィール"}の年収${formatCompactYen(result.incomeContext.annualIncome)}を参照。${result.incomeContext.source}`}/></div></div></Panel><Panel><div className="flex gap-3"><CheckCircle2 className="mt-1 shrink-0 text-[#3C8A68]"/><div><Title title="実行候補・配分ルール" text={result.implementationCandidates.join(" ")}/></div></div></Panel><Panel><div className="flex gap-3"><ShieldCheck className="mt-1 shrink-0 text-[#3C8A68]"/><div><Title title="実行ルール" text="市場データが取得できない場合は追加買付を保留します。配分乖離が閾値内なら、保有・定額積立を優先します。注文・売買はこのアプリから実行しません。"/></div></div></Panel><Panel className="border-[#F1DABB] bg-[#FFF9EF]"><div className="flex gap-3"><AlertTriangle className="mt-1 shrink-0 text-[#AC7431]"/><div><Title title="前提と限界" text="確率モデルは過去の約束ではありません。税制・教育費・年金・金利は変わり得るため、年1回と大きな家計変化時に更新してください。"/></div></div></Panel><Panel><div className="flex gap-3"><Info className="mt-1 shrink-0 text-[#507C6E]"/><div><Title title="前提・出所" text={`${result.assumptions.join(" ")} 出所: 国税庁「No.1135 小規模企業共済等掛金控除」、金融庁NISA特設ウェブサイト。詳細はプロジェクト内の recommendation_sources.md を参照。`}/></div></div></Panel></div></section>
    </>}
  </main></DashboardLayout>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/[.08] p-4"><p className="text-[10px] text-white/45">{label}</p><p className="mt-2 font-serif text-2xl text-[#A9EDCE]">{value}</p></div>; }
function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-[1.5rem] border border-[#DCE2DC] bg-white p-5 sm:p-6 ${className}`}>{children}</section>; }
function Title({ title, text }: { title: string; text: string }) { return <div><h2 className="font-serif text-2xl text-[#1B2E2B]">{title}</h2><p className="mt-1 text-xs leading-5 text-[#728078]">{text}</p></div>; }
